name: flutter_banco_douro
description: "Aplicativo para avisar de compromissos e pagamentos"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner.png
    - assets/images/icon_add_account.png
    - assets/images/logo.png
    - assets/images/stars.png
    - assets/images/calendar.png
    - assets/images/finance.png
