// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgN9NzjMsL0ZpcRHpSgAz8WLkCe3x-368',
    appId: '1:346438293261:web:a0df6e770d402bd78b8244',
    messagingSenderId: '346438293261',
    projectId: 'cadastroeventos-1f7e8',
    authDomain: 'cadastroeventos-1f7e8.firebaseapp.com',
    storageBucket: 'cadastroeventos-1f7e8.firebasestorage.app',
    measurementId: 'G-LBVJQDSE72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQDt7YvD7EB1nZGOH_wLdRRHszgphsoc',
    appId: '1:346438293261:android:03dab68673ffc09d8b8244',
    messagingSenderId: '346438293261',
    projectId: 'cadastroeventos-1f7e8',
    storageBucket: 'cadastroeventos-1f7e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5AYD4eqQpDsrFcbQyakeAN4DSr_7SIuo',
    appId: '1:346438293261:ios:ae545b41e81aa9908b8244',
    messagingSenderId: '346438293261',
    projectId: 'cadastroeventos-1f7e8',
    storageBucket: 'cadastroeventos-1f7e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterBancoDouro.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5AYD4eqQpDsrFcbQyakeAN4DSr_7SIuo',
    appId: '1:346438293261:ios:739d5ce49ae3fca78b8244',
    messagingSenderId: '346438293261',
    projectId: 'cadastroeventos-1f7e8',
    storageBucket: 'cadastroeventos-1f7e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterBancoDouro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgN9NzjMsL0ZpcRHpSgAz8WLkCe3x-368',
    appId: '1:346438293261:web:873f3c640a985d858b8244',
    messagingSenderId: '346438293261',
    projectId: 'cadastroeventos-1f7e8',
    authDomain: 'cadastroeventos-1f7e8.firebaseapp.com',
    storageBucket: 'cadastroeventos-1f7e8.firebasestorage.app',
    measurementId: 'G-M38Q30YEWR',
  );

}